server:
  port: 88
  servlet:
    encoding:
      charset: UTF-8
      force: true
    session:
      timeout: 10m
spring:
  messages:
    basename: messages/message
    encoding: utf-8
    cache-duration: 10
    fallback-to-system-locale: false

  mvc:
    view:
      prefix: /views/
      suffix: .jsp

  datasource:
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    url: jdbc:log4jdbc:mysql://sb2.cjic2osskepb.ap-northeast-2.rds.amazonaws.com:3306/fromits?characterEncoding=utf8
    #    driver-class-name: com.mysql.cj.jdbc.Driver
    #    url: jdbc:mysql://127.0.0.1:3306/shopdb?characterEncoding=utf8&serverTimezone=Asia/Seoul
    username: fromits
    password: ENC(UqaVWjPjT+QlN6ZGd/p62w==)
mybatis:
  type-aliases-package: com.fromits.app.dto
  mapper-locations: classpath:/mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
logging:
  level:
    root: info
